[pytest]
pythonpath = .
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
testpaths = tests
addopts = --tb=short -p no:cacheprovider --import-mode=importlib
markers =
    write: marks tests that write to the database (deselect with '-m "not write"')


