-- Drop tables in reverse order to handle foreign key constraints properly

DROP TABLE IF EXISTS Replays;

DROP TABLE IF EXISTS Players;

DROP TABLE IF EXISTS MEMORY;

DROP TABLE IF EXISTS USER;

DROP TABLE IF EXISTS PERSONALITY;

DROP TABLE IF EXISTS MOODS;

DROP TABLE IF EXISTS GOALS;

DROP TABLE IF EXISTS CORE_VALUES;

DROP TABLE IF EXISTS MOTIVATIONS;

DROP TABLE IF EXISTS MOOD_TYPE;

DROP TABLE IF EXISTS MAJOR_TRAITS;
