DROP TABLE IF EXISTS MAJOR_TRAITS RESTRICT;

DROP TABLE IF EXISTS MOOD_TYPE RESTRICT;

DROP TABLE IF EXISTS MOODS RESTRICT;

DROP TABLE IF EXISTS MOTIVATIONS RESTRICT;

DROP TABLE IF EXISTS CORE_VALUES RESTRICT;

DROP TABLE IF EXISTS GOALS RESTRICT;

DROP TABLE IF EXISTS PERSONALITY RESTRICT;

DROP TABLE IF EXISTS USER RESTRICT;

DROP TABLE IF EXISTS MEMORY RESTRICT;

DROP TABLE IF EXISTS Players RESTRICT;
